### ISSUE TITLE
ChronicleMap - Attempt to allocate #3 extra segment tier, 2 is maximum

### ISSUE THREAD

**Issue by patrick-tripp** [Unidata/tds#196]
I keep seeing this error. This FMRC worked fine last night but this morning I am getting the following error:

ERROR ucar.nc2.ft.fmrc.Fmrc: makeFmrcInv
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: ChronicleMap{name=GridDatasetInv, file=/usr/local/tomcat/content/thredds/cache/collection/GridDatasetInv.dat, identityHashCode=401224888}: Attempt to allocate #3 extra segment tier, 2 is maximum.
Possible reasons include:
 - you have forgotten to configure (or configured wrong) builder.entries() number
 - same regarding other sizing Chronicle Hash configurations, most likely maxBloatFactor(), averageKeySize(), or averageValueSize()
 - keys, inserted into the ChronicleHash, are distributed suspiciously bad. This might be a DOS attack
 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[guava-30.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[guava-30.1-jre.jar:?]
	...
Caused by: java.lang.IllegalStateException: ChronicleMap{name=GridDatasetInv, file=/usr/local/tomcat/content/thredds/cache/collection/GridDatasetInv.dat, identityHashCode=401224888}: Attempt to allocate #3 extra segment tier, 2 is maximum.
Possible reasons include:
...
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[guava-30.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-30.1-jre.jar:?]
	... 66 more

**Comment by patrick-tripp** [comment]
I was able to resolve this by modifying the code where the ChronicleMapBuilder creates the cache. We have about 1.5 million unique files we are indexing. Our resultant GridDatasetInv.dat file is about 8GB with the following adjustment. Note: the cache is only created once and needs to be deleted after redeploying an updated war file. Fortunately, this implementation indexes files a lot faster than the previous BerkeleyDB implementation. Thanks!

GridInventoryCacheChronicle.java init():
    if (cache == null) {
      cache = ChronicleMapBuilder.of(String.class, byte[].class).name("GridDatasetInv")
          .averageKey("/data/project/analysis/file.ext")
          .averageValueSize(4096)
          .entries(1500000)
          .maxBloatFactor(4.0)
          .createOrRecoverPersistedTo(dbFile.toFile());
    }
