### ISSUE TITLE
ERROR thredds.featurecollection.InvDatasetFcFmrc: Error making catalog

### ISSUE THREAD

**Issue by mjfmi** [Unidata/tds#275]
We have a problem with catalog requests failing, i.e. we get a FileNotFound because it's never created. Deleting the cache seems to help temporarily but what normally happens now is this:

`[2022-08-30T17:51:03.748+0300] ERROR thredds.featurecollection.InvDatasetFcFmrc: Error making catalog for silam_glob06_v5_8
java.lang.NullPointerException: null
	at ucar.nc2.ft.fmrc.FmrcDataset.getRunDates(FmrcDataset.java:105) ~[cdm-core-5.5.3.jar:5.5.3]
	at ucar.nc2.ft.fmrc.Fmrc.getRunDates(Fmrc.java:158) ~[cdm-core-5.5.3.jar:5.5.3]
	at thredds.featurecollection.InvDatasetFcFmrc.makeRunDatasets(InvDatasetFcFmrc.java:290) ~[classes/:5.4]
	at thredds.featurecollection.InvDatasetFcFmrc.makeCatalogRuns(InvDatasetFcFmrc.java:242) ~[classes/:5.4]
	at thredds.featurecollection.InvDatasetFcFmrc.makeCatalog(InvDatasetFcFmrc.java:182) [classes/:5.4]
	at thredds.core.CatalogManager.makeDynamicCatalog(CatalogManager.java:118) [classes/:5.4]
	at thredds.core.CatalogManager.getCatalog(CatalogManager.java:75) [classes/:5.4]
	at thredds.server.catalogservice.CatalogServiceController.handleRequest(CatalogServiceController.java:55) [classes/:5.4]
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.20.jar:5.3.20]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.20.jar:5.3.20]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.75]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.6.5.jar:5.6.5]
	at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:50) [classes/:5.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
	at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:90) [classes/:5.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
	at thredds.servlet.filter.HttpHeadFilter.doFilter(HttpHeadFilter.java:47) [classes/:5.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.6.5.jar:5.6.5]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.6.5.jar:5.6.5]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.20.jar:5.3.20]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196) [catalina.jar:8.5.75]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.75]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [catalina.jar:8.5.75]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:8.5.75]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) [catalina.jar:8.5.75]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.75]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.75]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:366) [catalina.jar:8.5.75]
	at org.apache.coyote.http2.StreamProcessor.service(StreamProcessor.java:389) [tomcat-coyote.jar:8.5.75]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.75]
	at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:84) [tomcat-coyote.jar:8.5.75]
	at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35) [tomcat-coyote.jar:8.5.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:8.5.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:8.5.75]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.75]
	at java.lang.Thread.run(Thread.java:829) [?:?]
`

**Comment by mjfmi** [comment]
- Thredds 5.4
- To be specific, the failed request results in e.g. "FileNotFound: silam_europe_v5_7_2/catalog.xml"
- catalog.xml below
 
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<catalog xmlns="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="FMI SILAM CATALOG" xsi:schemaLocation="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0 http://www.unidata.ucar.edu/schemas/thredds/InvCatalog.1.0.6.xsd">
<service name="all" base="" serviceType="compound">
<service name="odap" serviceType="OpenDAP" base="/thredds/dodsC/"/>
<service name="dap4" serviceType="DAP4" base="/thredds/dap4/"/>
<service name="http" serviceType="HTTPServer" base="/thredds/fileServer/"/>

<service name="ncssGrid" serviceType="NetcdfSubset" base="/thredds/ncss/grid/"/>
</service>
<catalogRef xlink:title="Globemission data" xlink:href="catalog_globemission.xml" name="globemission"/>
<catalogRef xlink:title="IS4FIRES_v2_0" xlink:href="catalog_IS4FIRES.xml" name="IS4FIRES"/>

<featureCollection name="daily_silam_glob_v5_5_1" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="dailysilam_glob_v5_5_1">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best ConstantForecasts"/>
<collection spec="/data/threddsdata/daily_v5_5_1/glob_v5_5_1/SILAM-AQstat-glob_v5_5_1_#yyyyMMdd#00.nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="daily_silam_china_v5_5_1" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="daily_silam_china_v5_5_1">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best ConstantForecasts"/>
<collection spec="/data/threddsdata/daily_v5_5_1/china_v5_5_1/SILAM-AQstat-china_v5_5_1_#yyyyMMdd#00.nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="daily_silam_glob_v5_7_1" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="dailysilam_glob_v5_7_1">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best ConstantForecasts"/>
<collection spec="/data/threddsdata/daily_v5_7_1/glob_v5_7_1/SILAM-AQstat-glob_v5_7_1_#yyyyMMdd#00.nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="dust_glob01_v5_7_2" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="dust_glob01_v5_7_2">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best ConstantForecasts"/>
<collection spec="/data/threddsdata/glob01_v5_7_2/SILAM-dust-glob01_v5_7_2_#yyyyMMdd#00_[0-9][0-9][0-9].nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_allergy_risk" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_allergy_risk">
<fmrcConfig regularize="true" datasetTypes="Files"/>
<collection spec="/data/threddsdata/allergy_risk/allergy_risk_#yyyyMMdd#.nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_china_v5_5_1" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_china_v5_5_1">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/china_v5_5_1/SILAM-AQ-china_v5_5_1_#yyyyMMdd#[0-9][0-9]_[0-9][0-9][0-9].nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_europe_pollen_v5_8" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_europe_pollen_v5_8">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/europe_v5_8/SILAM-POLLEN-europe_v5_8_#yyyyMMdd#00.nc4$"/>
<update startup="true" rescan="51 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_europe_v5_8" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_europe_v5_8">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/europe_v5_8/SILAM-AQ-europe_v5_8_#yyyyMMdd#[0-9][0-9]_[0-9][0-9][0-9].nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_glob_v5_5_1" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_glob_v5_5_1">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/glob_v5_5_1/SILAM-AQ-glob_v5_5_1_#yyyyMMdd#00_[0-9][0-9][0-9].nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_glob_v5_7_1" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_glob_v5_7_1">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/glob_v5_7_1/SILAM-AQ-glob_v5_7_1_#yyyyMMdd#00_[0-9][0-9][0-9].nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_glob06_v5_8" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_glob06_v5_8">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/glob06_v5_8/SILAM-AQ-glob06_v5_8_#yyyyMMdd#00_[0-9][0-9][0-9].nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_regional_pollen_v5_7" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_regional_pollen_v5_7">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/regional_v5_7/SILAM-POLLEN-regional_v5_7_#yyyyMMddHH#.nc4$"/>
<update startup="true" rescan="51 * * * * ? *"/>
</featureCollection>
<featureCollection name="silam_regional_v5_7" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_regional_v5_7">
<fmrcConfig regularize="true" datasetTypes="Runs Files Best"/>
<collection spec="/data/threddsdata/regional_v5_7/SILAM-AQ-regional_v5_7_#yyyyMMdd#[0-9][0-9]_[0-9][0-9][0-9].nc4$"/>
<update startup="true" rescan="50 * * * * ? *"/>
</featureCollection>

</catalog>`

**Comment by mjfmi** [comment]
-  Thredds 5.4
- To be specific, the failed request results in e.g. "FileNotFound: silam_europe_v5_7_2/catalog.xml"
- catalog.xml here (I couldn't figure out how to paste XML or attach it as a file): https://pastebin.com/19GJbqYQ

**Comment by tdrwenski** [comment]
Thanks for the extra info! I don't see the path `silam_europe_v5_7_2` in the catalog you sent, but based on the errors I am guessing it is a `featureCollection` with featureType `FMRC` like the others in your catalog (maybe it is in the catalogs you are bringing in with `catalogRef` elements?)
 
 This first error: "FileNotFound: silam_europe_v5_7_2/catalog.xml" sounds like it can't find any data files for that specific featureCollection. Just to rule that out, can you check that the `collection spec` element for your feature collection with `path=silam_europe_v5_7_2` has the correct path to your data files?

Also, what method are you using to delete the cache, for instance are you doing that through the admin service?

**Comment by rkouznetsov** [comment]
Sorry. Please try `silam_europe_v5_8`.:
http://thredds.silam.fmi.fi/thredds/catalog/silam_europe_v5_8/catalog.html

The files are perfectly accessible via files 'view'.  Exactly the same description of the FMRC in TDS 4.6 works like a charm providing both files and 'Forecast Model Run' views:
```
    <featureCollection name="silam_europe_v5_8" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_europe_v5_8">                                            
      <fmrcConfig regularize="true" datasetTypes="Runs Files Best" />
          <collection spec="/data/threddsdata/europe_v5_8/SILAM-AQ-europe_v5_8_#yyyyMMdd#[0-9][0-9]_[0-9][0-9][0-9].nc4$"/>
          <update startup="true" rescan="50 * * * * ? *" />
  </featureCollection>


```
Please check https://silam.fmi.fi/thredds/catalog/silam_europe_v5_8/catalog.html for the same data at the TDS 4.6 server.

The cache was deleted in a brutal way by killing tomcat and cleaning the content/thredds/cache directory. 

Thank you!

**Comment by rkouznetsov** [comment]
After updating to thredds-5.5-SNAPSHOT.war "Forecast Model Runs" seem to work  (at the moment) for  http://thredds.silam.fmi.fi/thredds/catalog/silam_europe_v5_8/catalog.html

The issue is still there for 
http://thredds.silam.fmi.fi/thredds/catalog/silam_glob06_v5_8/catalog.html

**Comment by haileyajohnson** [comment]
Can you post the section of you catalog that's configuring the collection that isn't working?
The `<featureCollection name="silam_glob06_v5_8">` element, that is?

**Comment by haileyajohnson** [comment]
My best guess is that you need to configure your FeatureCollection cache as described [here](https://docs.unidata.ucar.edu/tds/current/userguide/tds_config_ref.html#featurecollection-cache), specifically by setting the `<maxEntries>` and `<maxBloatFactor>`.  You have many more files in the not working dataset than the working one, and the `nullpointerexception` from your logs  it being thrown from accessing the cache state, so increasing both those values might do the trick.

**Comment by rkouznetsov** [comment]
Thank you! The entry looks like:
```
  <featureCollection name="silam_glob06_v5_8" collectionType="ForecastModelRuns" featureType="FMRC" serviceName="all" path="silam_glob06_v5_8">
      <fmrcConfig regularize="true" datasetTypes="Runs Files Best" />
          <collection spec="/data/threddsdata/glob06_v5_8/SILAM-AQ-glob06_v5_8_#yyyyMMdd#00_[0-9][0-9][0-9].nc4$"/>
          <update startup="true" rescan="50 * * * * ? *" />
  </featureCollection>
```
I got a bit confused by `<maxEntries>`: I could not find any place where the meaning of "entry" would be clarified: Is it a file, a timestep, a forecast, a variable in a forecast, or something else?

Same applies to  `<maxBloatFactor>`..
Any guidance on a choice for these parameters would be of help.  

In any case `nullpointerexception` is, probably not the most clear diagnostic for the problem.

**Comment by rkouznetsov** [comment]
Also this might be of help (from fmrc.log):
```
[2022-09-12T16:02:50.010+0300] INFO  thredds.featurecollection.InvDatasetFeatureCollection: silam_glob06_v5_8: scan found changes 2022-09-12T16:02:50.010+0300: nnew=168, nchange=0, ndelete=0
[2022-09-12T16:02:50.065+0300] ERROR ucar.nc2.ft.fmrc.Fmrc: makeFmrcInv
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: ChronicleMap{name=GridDatasetInv, file=/content/thredds/cache/collection/GridDatasetInv.dat, identityHashCode=1659873263}: Attempt to allocate #3 extra segment tier, 2 is maximum.
Possible reasons include:
 - you have forgotten to configure (or configured wrong) builder.entries() number
 - same regarding other sizing Chronicle Hash configurations, most likely maxBloatFactor(), averageKeySize(), or averageValueSize()
 - keys, inserted into the ChronicleHash, are distributed suspiciously bad. This might be a DOS attack
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[guava-30.1-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[guava-30.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848) ~[guava-30.1-jre.jar:?]
        at ucar.nc2.ft.fmrc.GridDatasetInv.open(GridDatasetInv.java:62) ~[cdm-core-5.5.3.jar:5.5.3]
        at ucar.nc2.ft.fmrc.Fmrc.makeFmrcInv(Fmrc.java:287) [cdm-core-5.5.3.jar:5.5.3]
        at ucar.nc2.ft.fmrc.Fmrc.update(Fmrc.java:222) [cdm-core-5.5.3.jar:5.5.3]
        at thredds.featurecollection.InvDatasetFcFmrc.updateCollection(InvDatasetFcFmrc.java:140) [classes/:5.4]
        at thredds.featurecollection.InvDatasetFeatureCollection.update(InvDatasetFeatureCollection.java:310) [classes/:5.4]
        at thredds.featurecollection.InvDatasetFcFmrc.update(InvDatasetFcFmrc.java:122) [classes/:5.4]
        at thredds.featurecollection.InvDatasetFeatureCollection.processEvent(InvDatasetFeatureCollection.java:210) [classes/:5.4]
        at jdk.internal.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) [guava-30.1-jre.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144) [guava-30.1-jre.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) [guava-30.1-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: ChronicleMap{name=GridDatasetInv, file=/content/thredds/cache/collection/GridDatasetInv.dat, identityHashCode=1659873263}: Attempt to allocate #3 extra segment tier, 2 is maximum.
Possible reasons include:
 - you have forgotten to configure (or configured wrong) builder.entries() number
 - same regarding other sizing Chronicle Hash configurations, most likely maxBloatFactor(), averageKeySize(), or averageValueSize()
 - keys, inserted into the ChronicleHash, are distributed suspiciously bad. This might be a DOS attack
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.allocateTier(VanillaChronicleHash.java:822) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.impl.CompiledMapQueryContext.nextTier(CompiledMapQueryContext.java:3131) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.impl.CompiledMapQueryContext.alloc(CompiledMapQueryContext.java:3492) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initEntryAndKey(CompiledMapQueryContext.java:3510) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.impl.CompiledMapQueryContext.putEntry(CompiledMapQueryContext.java:4003) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.impl.CompiledMapQueryContext.doInsert(CompiledMapQueryContext.java:4192) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.MapEntryOperations.insert(MapEntryOperations.java:153) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.impl.CompiledMapQueryContext.insert(CompiledMapQueryContext.java:4115) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.MapMethods.put(MapMethods.java:88) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:856) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at thredds.featurecollection.cache.GridInventoryCacheChronicle.put(GridInventoryCacheChronicle.java:104) ~[classes/:5.4]
        at ucar.nc2.ft.fmrc.GridDatasetInv$GenerateInv.call(GridDatasetInv.java:112) ~[cdm-core-5.5.3.jar:5.5.3]
        at ucar.nc2.ft.fmrc.GridDatasetInv$GenerateInv.call(GridDatasetInv.java:68) ~[cdm-core-5.5.3.jar:5.5.3]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853) ~[guava-30.1-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[guava-30.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[guava-30.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[guava-30.1-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[guava-30.1-jre.jar:?]
        ... 18 more
[2022-09-12T16:02:50.088+0300] ERROR ucar.nc2.ft.fmrc.Fmrc: silam_glob06_v5_8: makeFmrcInv failed
```

**Comment by tdrwenski** [comment]
> I got a bit confused by <maxEntries>: I could not find any place where the meaning of "entry" would be clarified: Is it a file, a timestep, a forecast, a variable in a forecast, or something else?

I believe it is the maximum number of entries in the cache for FMRCs, so entries here means the number of files in your collection. The actual number of files needs to be less or equal to this value. The default is 1000 and I see ~670 in just your non working collection `silam_glob06_v5_8`. You should set this to your estimate for the total number of files you have in all your FMRC collections.

> Same applies to <maxBloatFactor>..
> Any guidance on a choice for these parameters would be of help.

This is the maximum number of times this cache is allowed to grow in size beyond the maxEntries, and the default is 1, so it can never grow. If you may theoretical have more FMRC files than your `maxEntries`, this number should be that theoretical max divided by the `maxEntries`. You could also just start by setting this to, for instance, 2 and see if that helps.

> In any case nullpointerexception is, probably not the most clear diagnostic for the problem.

Yes, that is indeed not a very helpful message. However, I think the error you found in your log points to the actual problem.

I hope that helps!

**Comment by rkouznetsov** [comment]
Thank you! I have added
```
 <FeatureCollection>
  <dir>${tds.content.root.path}/thredds/cache/collection/</dir>
  <maxEntries>10000</maxEntries>
  <maxBloatFactor>10</maxBloatFactor>
</FeatureCollection>
```
to `threddsConfig.xml`, and it seems to have done the trick. It took quite a while to initialize the whole thing. I wonder how safe it is to have x10 margin for these limits?
So translating "entries" to "files" and

**Comment by tdrwenski** [comment]
Glad you got it working! 

I am not an expert on the cache settings and Hailey may know more, but I believe that effect of setting the `maxEntries` too high is that it will reserve more disk space than is needed for the cache. However, setting this too low could cause the cache to need to increase in size multiple times, and that may cause performance issues. The ChronicleMap (library we use for the cache) documentation says:

> Chronicle Map works progressively slower when the actual size grows far beyond the configured size

So if disk space isn't an issue I think it is better to set `maxEntries` a bit too high.

I will have a look if we can clarify what is meant by "entries" in the documentation-- that terminology comes from ChronicleMap but may indeed be unclear to our users. And I'll see if anything from our discussion here could be added to the docs about those settings.

Let us know if you have other questions.

**Comment by rkouznetsov** [comment]
Given the size of our datasets, the space occupied by caches is the least of our concerns :)
Thank you for your support!
