### ISSUE TITLE
DAP4 exception when a ncml file it's served

### ISSUE THREAD

**Issue by cofinoa** [Unidata/tds#30]
When a file in `.ncml` format it's been accessed using DAP4 service, the following exception it's been raised: 
```
 <Error httpcode="400"> <Message>dap4.core.util.DapException: CDMDSP: cannot process: /oceano/gmeteo/WORK/zequi/DATASETS/cmip5-esm-subset-day/ncmls/cmip6_CMIP_BCC_BCC-CSM2-MR_esm-hist_r1i1p1f1_gn.ncml at dap4.cdm.dsp.CDMDSP.open(CDMDSP.java:121) at dap4.cdm.dsp.CDMDSP.open(CDMDSP.java:36) at dap4.servlet.DapCache.open(DapCache.java:94) at dap4.servlet.DapController.doDMR(DapController.java:307) at dap4.servlet.DapController.handleRequest(DapController.java:230) at thredds.server.dap4.Dap4Controller.handleRequest(Dap4Controller.java:74) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:53) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) at thredds.servlet.filter.RequestCORSFilter.doFilterInternal(RequestCORSFilter.java:53) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:92) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) at thredds.servlet.filter.HttpHeadFilter.doFilter(HttpHeadFilter.java:46) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:318) at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:192) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502) at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:877) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1519) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1475) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: dap4.core.util.DapException: java.io.IOException: java.io.IOException: Cant read /oceano/gmeteo/WORK/zequi/DATASETS/cmip5-esm-subset-day/ncmls/cmip6_CMIP_BCC_BCC-CSM2-MR_esm-hist_r1i1p1f1_gn.ncml: not a valid CDM file. at dap4.cdm.dsp.CDMDSP.createNetcdfFile(CDMDSP.java:1090) at dap4.cdm.dsp.CDMDSP.open(CDMDSP.java:117) ... 64 more Caused by: java.io.IOException: java.io.IOException: Cant read /oceano/gmeteo/WORK/zequi/DATASETS/cmip5-esm-subset-day/ncmls/cmip6_CMIP_BCC_BCC-CSM2-MR_esm-hist_r1i1p1f1_gn.ncml: not a valid CDM file. at ucar.nc2.NetcdfFile.open(NetcdfFile.java:498) at dap4.cdm.dsp.CDMDSP.createNetcdfFile(CDMDSP.java:1081) ... 65 more Caused by: java.io.IOException: Cant read /oceano/gmeteo/WORK/zequi/DATASETS/cmip5-esm-subset-day/ncmls/cmip6_CMIP_BCC_BCC-CSM2-MR_esm-hist_r1i1p1f1_gn.ncml: not a valid CDM file. at ucar.nc2.NetcdfFile.open(NetcdfFile.java:895) at ucar.nc2.NetcdfFile.open(NetcdfFile.java:495) ... 66 more </Message> <Context>http://spock.meteo.unican.es/tds5/dap4/cmip6/cmip6_CMIP_BCC_BCC-CSM2-MR_esm-hist_r1i1p1f1_gn.ncml.dmr.xml</Context>
```
The example endpoint can be found here http://spock.meteo.unican.es/tds5/catalog/catalogs/cmip6.html?dataset=cmip6_CMIP_BCC_BCC-CSM2-MR_esm-hist_r1i1p1f1_gn
 
@zequihg50

**Comment by lesserwhirls** [comment]
@DennisHeimbigner - tagging you on this one.

**Comment by DennisHeimbigner** [comment]
I assume this is the same problem as described in
issue https://github.com/Unidata/netcdf-java/issues/58 .
I will be commenting at that issue and not here.

**Comment by cofinoa** [comment]
Yes. In fact tracing the exception on the DAP4 service has raised the issue on the netcdf-java repository.
