### ISSUE TITLE
Internal server error in DAP after some 24-hours of uptime..

### ISSUE THREAD

**Issue by rkouznetsov** [Unidata/tds#325]
Still same TDS-5.5.

There have been some errors during the server startup (see attached  extract from catalina.out) which might or might not be related.

Just requesting a single variable, one time stamp causes Error 500:
```
$ ncks --version
NCO netCDF Operators version 5.0.6 "Alanis" built by buildd on lcy02-amd64-027 at Feb  2 2022 18:28:56
ncks version 5.0.6
$  ncks -v NO2_column -d time,1 https://thredds.silam.fmi.fi/thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z
netcdf silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z {
  dimensions:
    lat = 297 ;
    lon = 600 ;
    time = 1 ;

  variables:
    float NO2_column(time,lat,lon) ;
      NO2_column:units = "molec/cm2" ;
      NO2_column:long_name = "Total NO2 column" ;
      NO2_column:_ChunkSizes = 2, 297, 600 ;
      NO2_column:coordinates = "time_run time lat lon " ;

    float lat(lat) ;
      lat:units = "degrees_north" ;
      lat:long_name = "latitude" ;
      lat:axis = "Y" ;
      lat:standard_name = "latitude" ;
      lat:_CoordinateAxisType = "Lat" ;
      lat:_ChunkSizes = 200 ;

    float lon(lon) ;
      lon:units = "degrees_east" ;
      lon:long_name = "longitude" ;
      lon:axis = "X" ;
      lon:standard_name = "longitude" ;
      lon:_CoordinateAxisType = "Lon" ;
      lon:_ChunkSizes = 200 ;

    double time(time) ;
      time:long_name = "Forecast time for ForecastModelRunCollection" ;
      time:standard_name = "time" ;
      time:calendar = "proleptic_gregorian" ;
      time:units = "hours since 2022-11-20 00:00:00.000 UTC" ;
      time:missing_value = NaN ;
      time:_CoordinateAxisType = "Time" ;

  data:
ERROR: nco_get_vara() failed to nc_get_vara() variable "NO2_column"
ERROR NC_EDAP Generic DAP error
HINT: NC_EDAP errors can occur when NCO is invoked with a request that a remote DAP server cannot meet, for example, due to the size of the required data transfer. One workaround might be to re-formulate the NCO command into more commands that each request smaller subsets/hyperslabs from the remote DAP server. However, there are a number of DAP-related errors, only one of which can be reported at a time. The others include: NC_EDAPSVC (-70, DAP server error), NC_EDDS and NC_EDMR (-72, Malformed or inaccessible DDS and Dap4 alias, respectively), NC_EDATADDS and NC_EDATADAP (-73, Malformed or inaccessible DATADDS and Dap4 alias, respectively), NC_EDAPURL and NC_EURL (-74, Malformed DAP URL and Malformed URL, respectively), NC_EDAPCONSTRAINT and NC_ECONSTRAINT (-75, Malformed DAP Constraint and Malformed Constraint, respectively). Few, if any, of these errors are expected to be caused by NCO, since NCO just relays user commands to the DAP server. It is more likely that the DAP syntax employed is incorrect, or there is an error with the DAP server, or the request exceeds the server constraints.
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_get_vara()
nco_err_exit(): ERROR Error code is -66. Translation into English with nc_strerror(-66) is "NetCDF: DAP failure"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
```

The TDS log looks like:
```
2022-11-25T10:35:45.405 +0200 [  86781782][   31400] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:35:45.495 +0200 [  86781872][   31400] INFO  - threddsServlet - Request Completed - 200 - -1 - 90
2022-11-25T10:35:45.507 +0200 [  86781884][   31401] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.das HTTP/2.0"
2022-11-25T10:35:45.673 +0200 [  86782050][   31401] INFO  - threddsServlet - Request Completed - 200 - -1 - 166
2022-11-25T10:35:45.721 +0200 [  86782098][   31402] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:35:45.809 +0200 [  86782186][   31402] INFO  - threddsServlet - Request Completed - 200 - -1 - 88
2022-11-25T10:35:45.985 +0200 [  86782362][   31404] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:35:46.073 +0200 [  86782450][   31404] INFO  - threddsServlet - Request Completed - 200 - -1 - 88
2022-11-25T10:35:46.081 +0200 [  86782458][   31405] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.das HTTP/2.0"
2022-11-25T10:35:46.256 +0200 [  86782633][   31405] INFO  - threddsServlet - Request Completed - 200 - -1 - 175
2022-11-25T10:35:46.299 +0200 [  86782676][   31406] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:35:46.391 +0200 [  86782768][   31406] INFO  - threddsServlet - Request Completed - 200 - -1 - 92
2022-11-25T10:35:46.487 +0200 [  86782864][   31407] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dods?hybrid,lat,lon,tim
e,time_offset,a,a_half,b,b_half,da,db HTTP/2.0"
2022-11-25T10:35:46.574 +0200 [  86782951][   31407] INFO  - threddsServlet - Request Completed - 200 - -1 - 87
2022-11-25T10:35:46.577 +0200 [  86782954][   31408] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dods?NO2_column.NO2_column%5b1%5d%5b0:296%5d%5b0:599%5d HTTP/2.0"
2022-11-25T10:35:46.664 +0200 [  86783041][   31408] ERROR - thredds.server.opendap.OpendapServlet - request= ReqState:
  serverClassName:    'null'
  dataSet:            'silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z'
  requestSuffix:      'dods'
  CE:                 'NO2_column.NO2_column[1][0:296][0:599]'
  compressOK:          false
  InitParameters:

java.lang.NullPointerException: null
2022-11-25T10:35:46.665 +0200 [  86783042][   31408] INFO  - threddsServlet - Request Completed - 500 - -1 - 88
2
```

If I request a grid subset, the backtrace is a bit longer. Request:
```
$ ncks -v NO2_column -d time,158 -d lat,207,249 -d lon,373,448 https://thredds.silam.fmi.fi/thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z
netcdf silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z {
  dimensions:
    lat = 43 ;
    lon = 76 ;
    time = 1 ;

  variables:
    float NO2_column(time,lat,lon) ;
      NO2_column:units = "molec/cm2" ;
      NO2_column:long_name = "Total NO2 column" ;
      NO2_column:_ChunkSizes = 2, 297, 600 ;
      NO2_column:coordinates = "time_run time lat lon " ;

    float lat(lat) ;
      lat:units = "degrees_north" ;
      lat:long_name = "latitude" ;
      lat:axis = "Y" ;
      lat:standard_name = "latitude" ;
      lat:_CoordinateAxisType = "Lat" ;
      lat:_ChunkSizes = 200 ;

    float lon(lon) ;
      lon:units = "degrees_east" ;
      lon:long_name = "longitude" ;
      lon:axis = "X" ;
      lon:standard_name = "longitude" ;
      lon:_CoordinateAxisType = "Lon" ;
      lon:_ChunkSizes = 200 ;

    double time(time) ;
      time:long_name = "Forecast time for ForecastModelRunCollection" ;
      time:standard_name = "time" ;
      time:calendar = "proleptic_gregorian" ;
      time:units = "hours since 2022-11-20 00:00:00.000 UTC" ;
      time:missing_value = NaN ;
      time:_CoordinateAxisType = "Time" ;

  data:
ERROR: nco_get_vara() failed to nc_get_vara() variable "NO2_column"
ERROR NC_EDAP Generic DAP error
HINT: NC_EDAP errors can occur when NCO is invoked with a request that a remote DAP server cannot meet, for example, due to the size of the required data transfer. One workaround might be to re-formulate the NCO command into more commands that each request smaller subsets/hyperslabs from the remote DAP server. However, there are a number of DAP-related errors, only one of which can be reported at a time. The others include: NC_EDAPSVC (-70, DAP server error), NC_EDDS and NC_EDMR (-72, Malformed or inaccessible DDS and Dap4 alias, respectively), NC_EDATADDS and NC_EDATADAP (-73, Malformed or inaccessible DATADDS and Dap4 alias, respectively), NC_EDAPURL and NC_EURL (-74, Malformed DAP URL and Malformed URL, respectively), NC_EDAPCONSTRAINT and NC_ECONSTRAINT (-75, Malformed DAP Constraint and Malformed Constraint, respectively). Few, if any, of these errors are expected to be caused by NCO, since NCO just relays user commands to the DAP server. It is more likely that the DAP syntax employed is incorrect, or there is an error with the DAP server, or the request exceeds the server constraints.
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_get_vara()
nco_err_exit(): ERROR Error code is -66. Translation into English with nc_strerror(-66) is "NetCDF: DAP failure"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
```

And the corresponding log:

```
2022-11-25T10:38:56.179 +0200 [  86972556][   31592] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/catalog/catalog.html?a=803 HTTP/1.1"
2022-11-25T10:38:56.182 +0200 [  86972559][   31592] INFO  - threddsServlet - Request Completed - 200 - -1 - 3
2022-11-25T10:38:56.649 +0200 [  86973026][   31593] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:38:56.737 +0200 [  86973114][   31593] INFO  - threddsServlet - Request Completed - 200 - -1 - 89
2022-11-25T10:38:56.770 +0200 [  86973147][   31594] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.das HTTP/2.0"
2022-11-25T10:38:56.965 +0200 [  86973342][   31594] INFO  - threddsServlet - Request Completed - 200 - -1 - 195
2022-11-25T10:38:57.012 +0200 [  86973389][   31595] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:38:57.108 +0200 [  86973485][   31595] INFO  - threddsServlet - Request Completed - 200 - -1 - 96
2022-11-25T10:38:57.275 +0200 [  86973652][   31597] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:38:57.363 +0200 [  86973740][   31597] INFO  - threddsServlet - Request Completed - 200 - -1 - 89
2022-11-25T10:38:57.392 +0200 [  86973769][   31598] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.das HTTP/2.0"
2022-11-25T10:38:57.559 +0200 [  86973936][   31598] INFO  - threddsServlet - Request Completed - 200 - -1 - 167
2022-11-25T10:38:57.603 +0200 [  86973980][   31599] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dds HTTP/2.0"
2022-11-25T10:38:57.691 +0200 [  86974068][   31599] INFO  - threddsServlet - Request Completed - 200 - -1 - 88
2022-11-25T10:38:57.784 +0200 [  86974161][   31600] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dods?hybrid,lat,lon,time,time_offset,a,a_half,b,b_half,da,db HTTP/2.0"
2022-11-25T10:38:57.869 +0200 [  86974246][   31600] INFO  - threddsServlet - Request Completed - 200 - -1 - 85
2022-11-25T10:38:57.872 +0200 [  86974249][   31601] INFO  - threddsServlet - Remote host: 193.166.212.104 - Request: "GET /thredds/dodsC/silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z.dods?NO2_column.NO2_column%5b158%5d%5b207:249%5d%5b373:448%5d HTTP/2.0"
2022-11-25T10:38:57.962 +0200 [  86974339][   31601] ERROR - thredds.server.opendap.OpendapServlet - request= ReqState:
  serverClassName:    'null'
  dataSet:            'silam_glob06_v5_8/runs/silam_glob06_v5_8_RUN_2022-11-23T00:00:00Z'
  requestSuffix:      'dods'
  CE:                 'NO2_column.NO2_column[158][207:249][373:448]'
  compressOK:          false
  InitParameters:

java.lang.IllegalStateException: DataBTree doesnt start with TREE
        at ucar.nc2.iosp.hdf5.DataBTree$Node.<init>(DataBTree.java:168) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.DataBTree$DataChunkIterator.<init>(DataBTree.java:128) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.DataBTree.getDataChunkIteratorFilter(DataBTree.java:67) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.H5tiledLayoutBB.<init>(H5tiledLayoutBB.java:94) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:149) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:126) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2122) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.reallyRead(Variable.java:817) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable._read(Variable.java:768) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:600) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:473) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:448) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:600) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft.fmrc.FmrcDataset.read(FmrcDataset.java:1063) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft.fmrc.FmrcDataset.access$200(FmrcDataset.java:74) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft.fmrc.FmrcDataset$ProxyReader1D.reallyRead(FmrcDataset.java:1015) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.dataset.VariableDS._read(VariableDS.java:448) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:600) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable.read(Variable.java:574) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at thredds.server.opendap.NcSDArray.read(NcSDArray.java:85) ~[classes/:5.5-SNAPSHOT]
        at thredds.server.opendap.NcSDGrid.read(NcSDGrid.java:46) ~[classes/:5.5-SNAPSHOT]
        at opendap.servers.SDGrid.serialize(SDGrid.java:426) ~[opendap-servlet-5.5-SNAPSHOT.jar:5.5-SNAPSHOT]
        at opendap.servers.CEEvaluator.send(CEEvaluator.java:306) ~[opendap-servlet-5.5-SNAPSHOT.jar:5.5-SNAPSHOT]
        at thredds.server.opendap.OpendapServlet.doGetDAP2Data(OpendapServlet.java:521) ~[classes/:5.5-SNAPSHOT]
        at thredds.server.opendap.OpendapServlet.doGet(OpendapServlet.java:182) [classes/:5.5-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) [spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.20.jar:5.3.20]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.20.jar:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.20.jar:5.3.20]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.6.5.jar:5.6.5]
        at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:50) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
        at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:90) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
        at thredds.servlet.filter.HttpHeadFilter.doFilter(HttpHeadFilter.java:47) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.6.5.jar:5.6.5]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.6.5.jar:5.6.5]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.20.jar:5.3.20]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.75]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:8.5.75]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) [catalina.jar:8.5.75]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.75]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:366) [catalina.jar:8.5.75]
        at org.apache.coyote.http2.StreamProcessor.service(StreamProcessor.java:389) [tomcat-coyote.jar:8.5.75]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.75]
        at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:84) [tomcat-coyote.jar:8.5.75]
        at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35) [tomcat-coyote.jar:8.5.75]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:8.5.75]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:8.5.75]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.75]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-11-25T10:38:57.979 +0200 [  86974356][   31601] INFO  - threddsServlet - Request Completed - 500 - -1 - 107
```

After restarting tomcat (though startup shows some errors, attached) both requests worked just fine...

Thank you!
[catalina.out-startup.gz](https://github.com/Unidata/tds/files/10090083/catalina.out-startup.gz)

**Comment by tdrwenski** [comment]
We have fixed a similar issue that I believe may also fix these errors (`DataBTree doesnt start with TREE`). Would you mind trying the latest snapshot to see if this does indeed resolve this issue? You can download the latest snapshot here:

https://downloads.unidata.ucar.edu/tds/5.5/thredds-5.5-SNAPSHOT.war

Regarding the errors you are seeing on start up in your Catalina.out-- it looks like they are only warnings, and I don't think they are a problem. I believe if you clean your webapps directory (remove everything you don't need from `$TOMCAT_HOME/webapps`), that will remove these warnings.

**Comment by rkouznetsov** [comment]
Thank  you! The issue seem to have gone after the update.
