### ISSUE TITLE
Java error from thredds

### ISSUE THREAD

**Issue by hawkeye-7** [Unidata/tds#328]
I am getting a Java error from thredds. Any advice would be helpful

2022-11-29T23:32:32.744 +0000 [  64956373][       9] INFO  - threddsServlet - Request Completed - 500 - -1 - 50
172.20.0.4 - - [29/Nov/2022:23:32:32 +0000] "GET /thredds/dodsC/master/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/v20191118/cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc.html HTTP/1.0" 500 49 "http://esgfdata-test-v4/thredds/catalog/esgcet/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/CMIP6.C4MIP.CSIRO.ACCESS-ESM1-5.1pctCO2-bgc.r1i1p1f1.Amon.cl.gn.v20191118.html?dataset=CMIP6.C4MIP.CSIRO.ACCESS-ESM1-5.1pctCO2-bgc.r1i1p1f1.Amon.cl.gn.v20191118.cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0" "150.203.248.112" [0.059]
2022-11-29T23:41:22.268 +0000 [  65485897][      10] INFO  - threddsServlet - Remote host: 150.203.248.112 - Request: "GET /thredds/dodsC/master/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/v20191118/cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc.html HTTP/1.0"
2022-11-29T23:41:22.275 +0000 [  65485904][      10] DEBUG - thredds.server.opendap.OpendapServlet - doGet(): User-Agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0
2022-11-29T23:41:22.276 +0000 [  65485905][      10] DEBUG - thredds.server.opendap.OpendapServlet - OpendapServlet: nominal url: http://esgfdata-test-v4/thredds/dodsC/master/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/v20191118/cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc.html?null
2022-11-29T23:41:22.276 +0000 [  65485905][      10] DEBUG - thredds.core.DatasetManager - DatasetHandler wants master/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/v20191118/cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc
2022-11-29T23:41:22.277 +0000 [  65485906][      10] ERROR - thredds.server.opendap.OpendapServlet - request= ReqState:
  serverClassName:    'null'
  dataSet:            'master/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/v20191118/cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc'
  requestSuffix:      'html'
  CE:                 ''
  compressOK:          true
  InitParameters:

java.lang.NullPointerException: null
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.findResourceControl(DatasetTrackerChronicle.java:193) ~[tdcommon-5.5-SNAPSHOT.jar:5.5-SNAPSHOT]
	at thredds.core.DatasetManager.resourceControlOk(DatasetManager.java:530) ~[classes/:5.5-SNAPSHOT]
	at thredds.core.DatasetManager.openNetcdfFile(DatasetManager.java:156) ~[classes/:5.5-SNAPSHOT]
	at thredds.core.TdsRequestedDataset.openAsNetcdfFile(TdsRequestedDataset.java:166) ~[classes/:5.5-SNAPSHOT]
	at thredds.core.TdsRequestedDataset.getNetcdfFile(TdsRequestedDataset.java:89) ~[classes/:5.5-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.getDataset(OpendapServlet.java:946) ~[classes/:5.5-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.doGetHTML(OpendapServlet.java:605) ~[classes/:5.5-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.doGet(OpendapServlet.java:188) [classes/:5.5-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.20.jar:5.3.20]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.20.jar:5.3.20]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.20.jar:5.3.20]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.6.5.jar:5.6.5]
	at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:50) [classes/:5.5-SNAPSHOT]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
	at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:90) [classes/:5.5-SNAPSHOT]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
	at thredds.servlet.filter.HttpHeadFilter.doFilter(HttpHeadFilter.java:47) [classes/:5.5-SNAPSHOT]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.6.5.jar:5.6.5]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.6.5.jar:5.6.5]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.6.5.jar:5.6.5]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.20.jar:5.3.20]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.57]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:8.5.57]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.57]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.57]
	at org.apache.catalina.valves.SSLValve.invoke(SSLValve.java:188) [catalina.jar:8.5.57]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) [catalina.jar:8.5.57]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.57]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615) [tomcat-coyote.jar:8.5.57]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.57]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-coyote.jar:8.5.57]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626) [tomcat-coyote.jar:8.5.57]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.57]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.57]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-11-29T23:41:22.282 +0000 [  65485911][      10] INFO  - threddsServlet - Request Completed - 500 - -1 - 15
172.20.0.4 - - [29/Nov/2022:23:41:22 +0000] "GET /thredds/dodsC/master/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/v20191118/cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc.html HTTP/1.0" 500 49 "http://esgfdata-test-v4/thredds/catalog/esgcet/CMIP6/C4MIP/CSIRO/ACCESS-ESM1-5/1pctCO2-bgc/r1i1p1f1/Amon/cl/gn/CMIP6.C4MIP.CSIRO.ACCESS-ESM1-5.1pctCO2-bgc.r1i1p1f1.Amon.cl.gn.v20191118.html?dataset=CMIP6.C4MIP.CSIRO.ACCESS-ESM1-5.1pctCO2-bgc.r1i1p1f1.Amon.cl.gn.v20191118.cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0" "150.203.248.112" [0.022]

**Comment by haileyajohnson** [comment]
What kind of dataset are you trying to access? Is it an FRMC dataset?

**Comment by hawkeye-7** [comment]
It is an ESGF NetCDF file. It's too large to attach here, but you can download it from this URL:

https://www.dropbox.com/s/fcfoprwdqieppa5/cl_Amon_ACCESS-ESM1-5_1pctCO2-bgc_r1i1p1f1_gn_024101-025012.nc?dl=0

**Comment by hawkeye-7** [comment]
Tried altering threddsConfig.xml to add:


  <FeatureCollection>
    <maxEntries>10000</maxEntries>
    <maxBloatFactor>10</maxBloatFactor>
  </FeatureCollection>

But this had no effect

**Comment by haileyajohnson** [comment]
Could you please share your fmrc.log file?

**Comment by hawkeye-7** [comment]
Nothing in the fmrc.log.

I can give you the catalina.log.

[catalina.log](https://github.com/Unidata/tds/files/10203479/catalina.log)

**Comment by hawkeye-7** [comment]
Here is the xml file:
[CMIP6.C4MIP.CSIRO.ACCESS-ESM1-5.1pctCO2-bgc.r1i1p1f1.Amon.cl.gn.v20191118.xml.zip](https://github.com/Unidata/tds/files/10204554/CMIP6.C4MIP.CSIRO.ACCESS-ESM1-5.1pctCO2-bgc.r1i1p1f1.Amon.cl.gn.v20191118.xml.zip)

**Comment by tdrwenski** [comment]
Thanks for the extra info! Would you mind also sharing your catalogInit.log file?

**Comment by hawkeye-7** [comment]
[container.txt](https://github.com/Unidata/tds/files/10273290/container.txt)

Docker writes all the logs into a single file. Not sure what came from where, so uploading  the entire file.

**Comment by tdrwenski** [comment]
Thanks for sending the logs! I see a FileNotFound (Permission denied) error:
```
datasetTracker.save() failed
java.io.FileNotFoundException: /opt/tomcat/content/thredds/cache/catalog/catTracker.dat (Permission denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:126) ~[?:?]
	at thredds.server.catalog.tracker.CatalogTracker.save(CatalogTracker.java:102) ~[tdcommon-5.5-SNAPSHOT.jar:5.5-SNAPSHOT]
	at thredds.core.ConfigCatalogInitialization.reread(ConfigCatalogInitialization.java:209) [classes/:5.5-SNAPSHOT]
	at thredds.core.ConfigCatalogInitialization.init(ConfigCatalogInitialization.java:126) [classes/:5.5-SNAPSHOT]
```

I am guessing there is an issue with either the path to your cache or the permissions of the cache directory but I am not able to reproduce this.

Could you tell me a little more about your docker config, specifically:
- Are you mounting volumes for the content and/or cache, for instance in your docker-compose.yml?
- Are you changing the content root path? For instance, in our [thredds-docker example](https://github.com/Unidata/thredds-docker) we set it in compose.env to be `TDS_CONTENT_ROOT_PATH=/usr/local/tomcat/content`

**Comment by hawkeye-7** [comment]
Not changing the content root path

 I have been looking at this. It could be a red herring, but the issue is that I need certain user/group permissions to access the shared data mounts. I was trying to force the user to be 13272 but the docker image wants to use the esgf user (1000). The thredds cache is owned by the esgf user, so 13272 cannot access it.   Unfortunately, rw access is not granted to the group. 

Will see if I can get things to work with the esgf user. 

(Put a .txt extension on the Dockerfile to help it upload)
[Dockerfile.txt](https://github.com/Unidata/tds/files/10377862/Dockerfile.txt)

**Comment by tdrwenski** [comment]
It definitely sounds like its related to the permissions you are setting! Did you figure out a way to get it working? I am not sure how much we can help since (if I understand correctly) you aren't using our [thredds-docker ](https://github.com/Unidata/thredds-docker), though maybe that repo could give you some ideas.

**Comment by tdrwenski** [comment]
Hi @hawkeye-7, are you still having problems related to this issue?

**Comment by hawkeye-7** [comment]
Yes. There were some things I wanted to try related to the user, but have not had the opportunity to do so.

**Comment by tdrwenski** [comment]
I will close this due to inactivity but feel free to reopen or open a new issue if you have further problems!
