### ISSUE TITLE
Throwable exception handled : java.lang.IllegalStateException: Invalid target for Validator 

### ISSUE THREAD

**Issue by nathanlcarlson** [Unidata/tds#33]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
```
# cat /usr/local/tomcat/webapps/thredds/META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Implementation-Title: THREDDS Data Server (TDS)
Implementation-Version: 5.0.0-beta5
Built-By: lesserwhirls
Implementation-Vendor-Id: edu.ucar
Implementation-URL: https://www.unidata.ucar.edu/software/thredds/curr
 ent/tds/TDS.html
Created-By: Gradle 3.5.1
Build-Jdk: 1.8.0_171
Built-On: 2018-09-10T18:14:26-0600
Implementation-Vendor: UCAR/Unidata
```
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
```
# uname -a
Linux [hostname] 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

# /usr/local/tomcat/bin/catalina.sh version
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Using CATALINA_PID:    /usr/local/tomcat/logs/catalina.pid
Server version: Apache Tomcat/8.5.39
Server built:   Mar 14 2019 11:24:26 UTC
Server number:  8.5.39.0
OS Name:        Linux
OS Version:     3.10.0-957.21.3.el7.x86_64
Architecture:   amd64
JVM Version:    1.8.0_212-b04
JVM Vendor:     Oracle Corporation
```
* a description of the issue with the steps needed to reproduce it

Using a homegrown remote catalog service that exists as a Flask application which generates the appropriate catalog XML by querying a back-end service. The following error occurs when clicking a dataset, a `.nc` link, within a catalog.
```
Throwable exception handled : java.lang.IllegalStateException: Invalid target for Validator [thredds.server.catalogservice.RemoteCatalogRequestValidator@568fb823]: thredds.server.catalogservice.DatasetContext@754d4e68
	at org.springframework.validation.DataBinder.assertValidators(DataBinder.java:568)
	at org.springframework.validation.DataBinder.setValidator(DataBinder.java:558)
	at thredds.server.catalogservice.RemoteCatalogServiceController.initBinder(RemoteCatalogServiceController.java:58)
...
```
The relevant function `org.springframework.validation.DataBinder.assertValidators` looks like this: https://github.com/spring-projects/spring-framework/blob/3a0f309e2c9fdbbf7fb2d348be861528177f8555/spring-context/src/main/java/org/springframework/validation/DataBinder.java#L538

Though, not the same springframework version, it is likely still relevant.

* Desired behavior

Get directed to an interface like this: 
https://aims3.llnl.gov/thredds/catalog/esgcet/298/CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.html?dataset=CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.rsutcs_Amon_E3SM-1-0_historical_r5i1p1f1_gr_200001-201412.nc

**Comment by nathanlcarlson** [comment]
This is not entirely claiming there is an issue within Thredds, but rather a combination of reporting a potential error as well as seeking any advice on remote catalogs. I will continue to investigate on the homegrown remote catalog service end and will be sure to report and close this issue if it is discovered to be an error on my end.

**Comment by nathanlcarlson** [comment]
I have learned the issue occurs when clicking a **_direct dataset_**. I also know that the _urlPath_ attribute does not actually exist on disk for now. I will do a test ensuring that the path exists.

**Comment by nathanlcarlson** [comment]
This also occurs on a fresh 5.0.0-beta7 release sourced from here: https://www.unidata.ucar.edu/downloads/tds/index.jsp

**Comment by nathanlcarlson** [comment]
It seems to be related to the DatasetContext class that was relatively recently developed. Here https://github.com/Unidata/tds/blob/19c22b07e550c6a4d1b00659a04051abae25160e/tds/src/main/java/thredds/server/catalogservice/CatalogViewContextParser.java#L345

**Comment by nathanlcarlson** [comment]
There are differences between the two controllers RemoteCatalogServiceController and CatalogServiceController. It seems the RemoteCatalogServiceController has these "validation" steps, whereas the CatalogServiceController does not. This can be seen in their respective class definitions.  The validation steps seem to ensure that the `params` constructor argument is valid. I do not have enough knowledge to know exactly what is going on, but hopefully this is a good starting place to resolve this issue.

**Comment by cofinoa** [comment]
Hi @nathanlcarlson, 

Just to check if I have understand your problem. 
Do you want to use the remote catalog service on TDS, to access Thredds catalog remotely generated by another "Flask" service? 

Your purpose it's to proxy the remote Flask service in your TDS server? The catalog service or data access service?

**Comment by nathanlcarlson** [comment]
Hi @cofinoa,

The idea is that instead of reading the catalog XML from the filesystem it is read via a network connection using HTTPS. If I understand the process correctly, this means the catalog XML can be generated dynamically (on demand) by an application. In this case I mentioned Flask because I've started such an application prototype using Flask, but it could be any thing. The application receives requests from Thredds that contain ID's for datasets or projects. It then uses these ID's to query Solr (since that is what ESGF is currently using) and get the metadata associated with the requested ID. Using this metadata it generates XML in the Thredds catalog format and responds to Thredds with this dynamically generated catalog.

**Comment by cofinoa** [comment]
I'm not sure if the remoteCatalogService it's what you are expecting: 

Form example, if this your remote dataset: 
https://aims3.llnl.gov/thredds/catalog/esgcet/298/CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.html?dataset=CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.rsutcs_Amon_E3SM-1-0_historical_r5i1p1f1_gr_200001-201412.nc

you can "proxy" it thru the UCAR remoteCatalogService like this:
http://thredds.ucar.edu/thredds/remoteCatalogService?command=subset&catalog=https://aims3.llnl.gov/thredds/catalog/esgcet/298/CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.xml&dataset=CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.rsutcs_Amon_E3SM-1-0_historical_r5i1p1f1_gr_200001-201412.nc

Some references on this are here (sorry by I don't find the current new ones): 
https://www.unidata.ucar.edu/software/tds/v4.3/tds4.2/reference/CatalogService.html

But, from your description, I'm not if this what you are looking for

**Comment by nathanlcarlson** [comment]
In that example, as well in Unidata's examples, the remote catalog is static content being served via HTTPS. I figure as long as the response is of MIME type "text/xml" and in the proper format it doesn't matter how the response is generated. Something like this:
```
....&catalog=https://my-catalog-generator.my.org/catalog/dataset/<datasetID>...
```

**Comment by lesserwhirls** [comment]
> I figure as long as the response is of MIME type "text/xml" and in the proper format it doesn't matter how the response is generated. Something like this:

I would think that's true, and I'd like for this to work. Does your app have a publicly accessible endpoint that I could hit to get a catalog response to play with? Or could I get an example of the xml that's failing to use to debug things locally?

**Comment by nathanlcarlson** [comment]
@lesserwhirls I could probably set up the endpoint to be public, but would prefer to first share the relevant XML that is generated. One moment.

**Comment by nathanlcarlson** [comment]
@lesserwhirls 
So I have two endpoints currently, the first uses a given project name to retrieve a set of ESGF datasets (currently just grabs 10) that belong to that project. That endpoint looks like this 
```
Endpoint: https://[catalog-generator-host]/catalog/project/<project-name>
Example: https://[catalog-generator-host]/catalog/project/CMIP6
# This is defined as a "catalogRef" in the base catalog.xml
<catalogRef ... xlink:href="https://[catalog-generator-host]/catalog/project/CMIP6"/>
```
Requests to this endpoint work as expected.
The other endpoint is for ESGF datasets.
This dataset endpoint is written to the `xlink:href` attribute in the catalog generated by requests to the project endpoint. For example:
```
# One for each dataset returned from the /catalog/project/CMIP6 request
...
<catalogRef ... xlink:href="https://[catalog-generator-host]/catalog/dataset/[ESGF Dataset ID]"/>
...
```
Requests to this second endpoint are also fine. This endpoint responds with something like the following, which I believe is the relevant XML:
```
<catalog name="[ESGF Dataset ID] Catalog" xmlns="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0 http://www.unidata.ucar.edu/schemas/thredds/InvCatalog.1.0.2.xsd">
    <service base="/thredds/fileServer/" desc="HTTPServer" name="HTTPServer" serviceType="HTTPServer" />
    <dataset ID="[ESGF Dataset ID]" name="[ESGF Dataset Name]" restrictAccess="esg-user">
        <property name="id" value="[ESGF Dataset ID]|[Datanode Hostname]" />
        <property name="version" value="20190110" />
        <property name="project" value="CMIP6" />
        <metadata inherited="true"><variables vocabulary="CF-1.0" />
            <dataType>Grid</dataType>
            <dataFormat>NetCDF</dataFormat>
        </metadata>
        <dataset ID="[ESGF Dataset ID].[ESGF Datafile ID]" name="[ESGF Datafile ID]" serviceName="HTTPServer" urlPath="[ESGF Datafile ID]">
            <property name="instance_id" value="[ESGF Dataset ID].[ESGF Datafile ID]" />
            <property name="size" value="24049324" />
            <property name="checksum" value="[checksum]" />
            <property name="checksum_type" value="SHA256" />
            <dataSize units="bytes">24049324</dataSize>
        </dataset>
    </dataset>
</catalog>
```
It is when attempting to access the element with `ID="[ESGF Dataset ID].[ESGF Datafile ID]"` via "SUBSET" that the error occurs. This is URL of the the failed request:
```
https://[my-thredds-server]/thredds/remoteCatalogService?command=SUBSET&catalog=https://[catalog-generator-host]/catalog/dataset/[ESGF Dataset ID]&dataset=[ESGF Dataset ID].[ESGF Datafile ID]
```
If the lack of real values is problematic let me know and I will make the endpoint available to you.

**Comment by nathanlcarlson** [comment]
@lesserwhirls

I just verified a suspicion: I am able to replicate this same error using the traditional static remote catalog procedure on 5.0.0-beta7. I used the following URL:
```
https://[5.0.0-beta7 Thredds Host]/thredds/remoteCatalogService?command=SUBSET&catalog=https://aims3.llnl.gov/thredds/catalog/esgcet/298/CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.xml&dataset=CMIP6.CMIP.E3SM-Project.E3SM-1-0.historical.r5i1p1f1.Amon.rsutcs.gr.v20190731.rsutcs_Amon_E3SM-1-0_historical_r5i1p1f1_gr_200001-201412.nc
```
