### ISSUE TITLE
NCSS Dataset Description link and data request throw errors

### ISSUE THREAD

**Issue by rjdave** [Unidata/tds#349]
tds-5.5-20230316.011558-110.war
Rocky Linux release 9.1 (Blue Onyx), AdoptOpenJDK 11.0.18+10, Tomcat 8.5.85

**Note that this dataset works without any errors in THREDDS 4.6.x.**

I have an FMRC dataset of ROMS model output that has the NetcdfSubset service enabled. The page to select variables displays, but when I click the "Dataset Description" link I get the following error on the webpage and in the log:
```
2023-03-16T16:19:50.497 -0400 [   7497222][      43] ERROR - thredds.server.TdsErrorHandling - uncaught exception
java.lang.NullPointerException: null
        at ucar.nc2.ft2.coverage.CoverageCoordAxis.getAttributes(CoverageCoordAxis.java:156) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CoverageDatasetCapabilities.writeAxis(CoverageDatasetCapabilities.java:141) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CoverageDatasetCapabilities.makeDatasetDescription(CoverageDatasetCapabilities.java:86) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at thredds.server.ncss.controller.NcssGridController.getDatasetDescriptionXml(NcssGridController.java:221) ~[classes/:5.5-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) [spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) [spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.23.jar:5.3.23]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:656) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.23.jar:5.3.23]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:765) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) [spring-security-web-5.7.5.jar:5.7.5]
        at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:50) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.5.jar:5.7.5]
        at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:90) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.5.jar:5.7.5]
        at thredds.servlet.filter.HttpHeadFilter.doFilter(HttpHeadFilter.java:47) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.5.jar:5.7.5]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) [spring-security-web-5.7.5.jar:5.7.5]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) [spring-security-web-5.7.5.jar:5.7.5]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.23.jar:5.3.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.85]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:8.5.85]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:8.5.85]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.85]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367) [catalina.jar:8.5.85]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639) [tomcat-coyote.jar:8.5.85]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.85]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:885) [tomcat-coyote.jar:8.5.85]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1688) [tomcat-coyote.jar:8.5.85]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.85]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:8.5.85]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:8.5.85]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.85]
        at java.lang.Thread.run(Thread.java:829) [?:?]
``` 

When I try to retrieve a single record of any variable I get the following error in the browser:
```
IllegalArgumentException: Dimension eta_rho does not exist
```

and the error below in the log:
```
2023-03-16T16:26:32.677 -0400 [   7899402][      50] WARN  - thredds.server.TdsErrorHandling - TDS Error
java.lang.IllegalArgumentException: Dimension eta_rho does not exist
        at ucar.nc2.Dimensions.makeDimensionsList(Dimensions.java:125) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Group$Builder.makeDimensionsList(Group.java:1252) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.Variable$Builder.setDimensionsByName(Variable.java:2025) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter.addCoordinateAxes(CFGridCoverageWriter.java:279) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter.writeFile(CFGridCoverageWriter.java:146) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at ucar.nc2.ft2.coverage.writer.CFGridCoverageWriter.write(CFGridCoverageWriter.java:113) ~[cdm-core-5.5.4-SNAPSHOT.jar:5.5.4-SNAPSHOT]
        at thredds.server.ncss.controller.NcssGridController.makeCFNetcdfFile(NcssGridController.java:172) ~[classes/:5.5-SNAPSHOT]
        at thredds.server.ncss.controller.NcssGridController.handleRequestGrid(NcssGridController.java:119) ~[classes/:5.5-SNAPSHOT]
        at thredds.server.ncss.controller.NcssGridController.handleRequest(NcssGridController.java:100) ~[classes/:5.5-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) [spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) [spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.23.jar:5.3.23]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.23.jar:5.3.23]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:656) [servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.23.jar:5.3.23]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:765) [servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) [spring-security-web-5.7.5.jar:5.7.5]
        at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:50) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.5.jar:5.7.5]
        at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:90) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.5.jar:5.7.5]
        at thredds.servlet.filter.HttpHeadFilter.doFilter(HttpHeadFilter.java:47) [classes/:5.5-SNAPSHOT]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) [spring-security-web-5.7.5.jar:5.7.5]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) [spring-security-web-5.7.5.jar:5.7.5]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) [spring-security-web-5.7.5.jar:5.7.5]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) [spring-web-5.3.23.jar:5.3.23]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) [spring-web-5.3.23.jar:5.3.23]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.1.jar:2.17.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.85]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:8.5.85]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:8.5.85]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:8.5.85]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) [catalina.jar:8.5.85]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:8.5.85]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367) [catalina.jar:8.5.85]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639) [tomcat-coyote.jar:8.5.85]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.85]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:885) [tomcat-coyote.jar:8.5.85]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1688) [tomcat-coyote.jar:8.5.85]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.85]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:8.5.85]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:8.5.85]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.85]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

I'm guessing the second error is causing the first error.

If click the "Dataset Description" link in **THREDDS 4.6**, eta_rho (and xi_rho) are listed in the "shape" attribute of many variables. When I download data in THREDDS 4.6, eta_rho and xi_rho are dimensions in the resulting NetCDF file.

**Comment by rjdave** [comment]
You can download a small part of the dataset to reproduce from our THREDDS 4.6 catalog [here](https://tds.marine.rutgers.edu/thredds/catalog/roms/doppio/2017_da/avg/files/catalog.html). I would suggest scrolling to the bottom and downloading several model runs (0001-00006.nc are one model run). Each run contains a hindcast and forecast. You will notice from the catalog entry below that we exclude our first day of hindcast from the "best" dataset.

```
      <featureCollection name="Averages"
                         featureType="FMRC"
                         harvest="true"
                         path="roms/doppio/2017_da/avg">
         <metadata inherited="true">
            <serviceName>all</serviceName>
            <dataType>Grid</dataType>
            <dataFormat>netCDF</dataFormat>
            <documentation type="summary">
               FMRC datasets for ROMS doppio real-time operational PSAS forecast system version 1 averages
            </documentation>
         </metadata>
         <collection spec="/path/to/roms/doppio/2017_da/avg/doppio_avg_#yyyyMMdd_HHmm#.*\.nc$"
                     name="doppio_2017_da_avg" />
         <update startup="nocheck" trigger="allow" />
         <protoDataset choice="Latest">
            <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" location="nc/cldc.mean.nc">
               <attribute name="title" type="String" value="ROMS doppio Real-Time Operational PSAS Forecast System Version 1 FMRC Averages" />
               <attribute name="summary" type="String" value="doppio" />
               <variable name="h">
                  <attribute name="standard_name" type="String" value="sea_floor_depth_below_sea_surface" />
               </variable>
               <variable name="zeta">
                  <attribute name="standard_name" type="String" value="sea_surface_elevation_anomaly" />
               </variable>
               <variable name="u">
                  <attribute name="standard_name" type="String" value="sea_water_x_velocity" />
               </variable>
               <variable name="v">
                  <attribute name="standard_name" type="String" value="sea_water_y_velocity" />
               </variable>
               <variable name="temp">
                  <attribute name="standard_name" type="String" value="sea_water_potential_temperature" />
               </variable>
               <variable name="salt">
                  <attribute name="standard_name" type="String" value="sea_water_practical_salinity" />
               </variable>
            </netcdf>
         </protoDataset>
         <fmrcConfig regularize="false" datasetTypes="TwoD Runs ConstantOffsets Files" >
            <dataset name="Best" offsetsGreaterEqual="25" />
         </fmrcConfig>
      </featureCollection>
```

Below are the relevant 'datasetRoot' and 'service' blocks from my main catalog:

```
   <datasetRoot location="/path/to/roms/"
                path="roms" />

   <service name="all" serviceType="Compound" base="">
      <service name="thisDODS" serviceType="OpenDAP" base="/thredds/dodsC/" />
      <service name="http" serviceType="HTTPServer" base="/thredds/fileServer/" />
      <service name="wms" serviceType="WMS" base="/thredds/wms/" />
      <service name="ncss" serviceType="NetcdfSubset" base="/thredds/ncss/grid/" />
   </service>
```

**Comment by tdrwenski** [comment]
This should be fixed in the latest snapshot which you can download here:

https://downloads.unidata.ucar.edu/tds/5.5/thredds-5.5-SNAPSHOT.war

**Comment by rjdave** [comment]
The latest snapshot fixes the nullptr exception in NCSS dataset description link. However, the IllegalArgumentException when trying to download any data remains.

**Comment by tdrwenski** [comment]
Sorry, I totally missed that in your original message. We will have another look!

**Comment by tdrwenski** [comment]
I had another look and it doesn't work because your dataset has multiple horizontal coordinate systems, which NCSS can't handle. NCSS handles [coverage datasets](https://docs.unidata.ucar.edu/netcdf-java/5.5/userguide/coverage_feature.html#overview) which have some restrictions:

> A CoverageCollection can only have a single HorizCoordSys, Calendar, and FeatureType.

The error message you are getting is super unhelpful, so I will see if I can improve that!

**Comment by tdrwenski** [comment]
TDS 4.x used grids and TDS 5.x uses coverages, so it works quite differently. So I think that TDS 5.x may have gotten stricter in which datasets NCSS can handle while still following the CF conventions.

**Comment by tdrwenski** [comment]
I am going to close this, but let us know if you have further questions about this!
