### ISSUE TITLE
Issue loading Catalogs

### ISSUE THREAD

**Issue by bsroth** [Unidata/tds#386]
Hello,

We are working on upgrading from 4.6.20 to 5.4 and I'm seeing an error while loading the some of our large grid data catalogs.  This catalog contains ~4500 different data sets that are themselves assembling specific grid sets.  After about 2500 load we get the errors below.  Any suggestions or help would be appreciated:

** ERROR: initializing catalog catalog.xml; ChronicleMap{name=null, file=/var/cache/thredds/catalog/chronicle.datasets.dat.1, identityHashCode=792220694}: Attempt to allocate #17 extra segment tier, 16 is maximum.
Possible reasons include:
 - you have forgotten to configure (or configured wrong) builder.entries() number
 - same regarding other sizing Chronicle Hash configurations, most likely maxBloatFactor(), averageKeySize(), or averageValueSize()
 - keys, inserted into the ChronicleHash, are distributed suspiciously bad. This might be a DOS attack
java.lang.IllegalStateException: ChronicleMap{name=null, file=/var/cache/thredds/catalog/chronicle.datasets.dat.1, identityHashCode=792220694}: Attempt to allocate #17 extra segment tier, 16 is maximum.
Possible reasons include:
 - you have forgotten to configure (or configured wrong) builder.entries() number
 - same regarding other sizing Chronicle Hash configurations, most likely maxBloatFactor(), averageKeySize(), or averageValueSize()
 - keys, inserted into the ChronicleHash, are distributed suspiciously bad. This might be a DOS attack
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.allocateTier(VanillaChronicleHash.java:822) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.nextTier(CompiledMapQueryContext.java:3131) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.alloc(CompiledMapQueryContext.java:3492) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initEntryAndKey(CompiledMapQueryContext.java:3510) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.putEntry(CompiledMapQueryContext.java:4003) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.doInsert(CompiledMapQueryContext.java:4192) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.MapEntryOperations.insert(MapEntryOperations.java:153) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.insert(CompiledMapQueryContext.java:4115) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.MapMethods.put(MapMethods.java:88) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:856) ~[chronicle-map-3.21ea6.jar:3.21ea6]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.trackDataset(DatasetTrackerChronicle.java:187) ~[tdcommon-5.4.jar:5.4]
	at thredds.core.ConfigCatalogInitialization.processDatasets(ConfigCatalogInitialization.java:409) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.processDatasets(ConfigCatalogInitialization.java:463) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.processDatasets(ConfigCatalogInitialization.java:463) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.checkCatalogToRead(ConfigCatalogInitialization.java:350) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.processDatasets(ConfigCatalogInitialization.java:458) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.checkCatalogToRead(ConfigCatalogInitialization.java:350) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.processDatasets(ConfigCatalogInitialization.java:458) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.checkCatalogToRead(ConfigCatalogInitialization.java:350) ~[classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.readRootCatalogs(ConfigCatalogInitialization.java:251) [classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.reread(ConfigCatalogInitialization.java:176) [classes/:5.4]
	at thredds.core.ConfigCatalogInitialization.init(ConfigCatalogInitialization.java:126) [classes/:5.4]
	at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:149) [classes/:5.4]
	at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:67) [classes/:5.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) [spring-web-5.3.20.jar:5.3.20]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) [spring-web-5.3.20.jar:5.3.20]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4492) [catalina.jar:8.5.87]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4950) [catalina.jar:8.5.87]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:8.5.87]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:711) [catalina.jar:8.5.87]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:688) [catalina.jar:8.5.87]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:661) [catalina.jar:8.5.87]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016) [catalina.jar:8.5.87]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903) [catalina.jar:8.5.87]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

ConfigCatalogInitializion stats
ConfigCatalogInitialization started 2023-06-23T17:18:40.548Z took 9.797000 secs using readMode=always
         catalogs=809
         datasets=103974
  trackedDatasets=23236
           restrict=0
            hasNcml=23236

      dataRoot=8
    featCollect=0
    datasetScan=7
    catalogScan=0
    datasetRoot=1

DatasetExt.total_count 23236
DatasetExt.total_nbytes 15544032
DatasetExt.avg_nbytes   669

restrict (0)

nAccess (3)
             0: count = 18959
             2: count = 61779
             3: count = 23236

serviceType (5)
    Service{ name=HTTPServer, base=/thredds/fileServer/, typeS=HTTPServer,desc=HTTPServer
  Property{name='requires_authorization', value='true'}
  Property{name='application', value='Web Browser'}
  Property{name='application', value='Web Script'}

}: count = 61779
    Service{ name=OpenDAPatNCCS, base=/thredds/dodsC/, typeS=OpenDAP,desc=OpenDAP
  Property{name='requires_authorization', value='false'}
  Property{name='application', value='Web Browser'}

}: count = 61779
    Service{ name=gridded, base=/thredds/dodsC/, typeS=OpenDAP,desc=Access dataset through OPeNDAP using the DAP2 protcol.}: count = 23236
    Service{ name=ncss, base=/thredds/ncss/grid/, typeS=NetcdfSubset,desc=A web service for subsetting CDM scientific datasets.}: count = 23236
    Service{ name=wms, base=/thredds/wms/, typeS=WMS,desc=Supports access to georegistered map images from geoscience datasets.}: count = 23236

ncmlAggSize (18)
             1: count = 11076
             2: count = 1064
             3: count = 3058
             4: count = 7036
             5: count = 372
             6: count = 27
             7: count = 27
             8: count = 96
             9: count = 60
            10: count = 196
            11: count = 16
            12: count = 9
            13: count = 120
            14: count = 12
            22: count = 3
            30: count = 48
           112: count = 12
           220: count = 4

ConfigCatalogInitializion finished took=10126 msecs

**Comment by haileyajohnson** [comment]
Have you configured the cache properties in your threddsConfig.xml? See [here](https://docs.unidata.ucar.edu/tds/current/userguide/tds_config_ref.html#featurecollection-cache)

**Comment by bsroth** [comment]
Yes we have it set very high as far as I am aware.

<FeatureCollection>
    <dir>/usr/local/tomcat/content/thredds/cache/collection/</dir>
      <maxEntries>100000</maxEntries>
      <maxBloatFactor>10</maxBloatFactor>
  </FeatureCollection>

I've also cleared the cache with each change to these features.

**Comment by tdrwenski** [comment]
Could you share your catalog or at least a typical dataset from the catalog? Do the datasets have large NcML? I am wondering if your issue is similar to https://github.com/Unidata/tds/issues/368

**Comment by bsroth** [comment]
Here is the catalog file entry where we start having issues.  Keep in mind I did not write these catalogs.

[cmip5.output1.NASA-GISS.GISS-E2-H.historicalMisc.mon.land.Lmon.r1i1p102.v20160427.txt](https://github.com/Unidata/tds/files/11898365/cmip5.output1.NASA-GISS.GISS-E2-H.historicalMisc.mon.land.Lmon.r1i1p102.v20160427.txt)

**Comment by tdrwenski** [comment]
You could try to change your ConfigCatalog [settings](https://docs.unidata.ucar.edu/tds/current/userguide/tds_config_ref.html#configuration-catalog) to have a larger `maxDatasets`, something like:
```
<ConfigCatalog>
  <maxDatasets>30000</maxDatasets>
</ConfigCatalog>
```
The default is 10,000 and it looks like from your catalogInit.log you have ~23,000 tracked datasets.

**Comment by bsroth** [comment]
Thank you this corrected thissue.

**Comment by bsroth** [comment]
closing
