### ISSUE TITLE
TDS not starting because of a ChronicleFileLockException

### ISSUE THREAD

**Issue by moskalenko** [Unidata/tds#422]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
5.4
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
RHEL8, java11
* a description of the issue with the steps needed to reproduce it
* There was an attempt to start another instance of TDS in the same directory tree, but on a different server. This resulted in a deadlock situation where now TDS cannot start at all. Removing cache to regenerate it doesn't help. 
E.g. /pubapps/icoast/app/prod/content/thredds/cache/collection/GridDatasetInv.dat gets regenerated after cache directory removal.
* The error that prevents TDS startup:

2023-09-27T17:52:55.381-0400 [     74897][        ] ERROR serverStartup: TdsInit: Failed initialize GridDatasetInv cache= /pubapps/icoast/app/prod/content/thredds/cache/collection/
net.openhft.chronicle.hash.ChronicleHashRecoveryFailedException: net.openhft.chronicle.hash.ChronicleFileLockException: Trying to release lock on file /pubapps/icoast/app/prod/content/thredds/cache/collection/Gr
idDatasetInv.dat that did not exist
        at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1926) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1716) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.ChronicleMapBuilder.recoverPersistedTo(ChronicleMapBuilder.java:1632) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1615) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1607) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1601) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at thredds.featurecollection.cache.GridInventoryCacheChronicle.init(GridInventoryCacheChronicle.java:66) ~[classes/:5.4]
        at thredds.server.config.TdsInit.readThreddsConfig(TdsInit.java:386) [classes/:5.4]
        at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:138) [classes/:5.4]
        at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:67) [classes/:5.4]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) [spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) [spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) [spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) [spring-context-5.3.20.jar:5.3.20]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) [spring-context-5.3.20.jar:5.3.20]
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) [spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) [spring-web-5.3.20.jar:5.3.20]
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) [spring-web-5.3.20.jar:5.3.20]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4697) [catalina.jar:8.5.55]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5163) [catalina.jar:8.5.55]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:8.5.55]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743) [catalina.jar:8.5.55]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719) [catalina.jar:8.5.55]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) [catalina.jar:8.5.55]
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125) [catalina.jar:8.5.55]
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1858) [catalina.jar:8.5.55]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: net.openhft.chronicle.hash.ChronicleFileLockException: Trying to release lock on file /pubapps/icoast/app/prod/content/thredds/cache/collection/GridDatasetInv.dat that did not exist
        at net.openhft.chronicle.map.FileLockUtil.lambda$releaseFileLock$2(FileLockUtil.java:78) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908) ~[?:?]
        at net.openhft.chronicle.map.FileLockUtil.releaseFileLock(FileLockUtil.java:75) ~[chronicle-map-3.21ea6.jar:3.21ea6]
        at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1909) ~[chronicle-map-3.21ea6.jar:3.21ea6]

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

**Comment by haileyajohnson** [comment]
> There was an attempt to start another instance of TDS in the same directory tree, but on a different server.
Do you mean two instances of the TDS on a single machine or is this a distribute architecture situation?
> This resulted in a deadlock situation where now TDS cannot start at all. Removing cache to regenerate it doesn't help.
E.g. /pubapps/icoast/app/prod/content/thredds/cache/collection/GridDatasetInv.dat gets regenerated after cache directory removal.
Neither TDS can start or the second TDS can't start? Is the first one running and regenerating the cache?

**Comment by moskalenko** [comment]
Hi @haileyajohnson . 

> > There was an attempt to start another instance of TDS in the same directory tree, but on a different server.
> 
> Do you mean two instances of the TDS on a single machine or is this a distribute architecture situation?

We didn't set up a distributed architecture. The tds instance on one server either got stuck or didn't get shut down when we started tds on another server independently. That second instance would get completely stuck early in the loading process until we stopped the first one.
 
> > This resulted in a deadlock situation where now TDS cannot start at all. Removing cache to regenerate it doesn't help.
> > E.g. /pubapps/icoast/app/prod/content/thredds/cache/collection/GridDatasetInv.dat gets regenerated after cache directory
> > removal.
> 
> Neither TDS can start or the second TDS can't start? Is the first one running and regenerating the cache?

We can't start TDS on either server now.

**Comment by haileyajohnson** [comment]
I not sure I completely understand your setup, but two instance of TDS cannot share a cache directory without conflicting, which is probably what go you into your current state.

As for getting out, it sounds like an orphaned java process is still running and holding files in your cache directory. You should check what process is holding that file and kill it (e.g.: `lsof {path}/content/thredds/cache/collection/GridDatasetInv.dat`)

**Comment by moskalenko** [comment]
We're not trying to run two instances. We are seeing the error I posted when we reboot the servers and try to run a single instance of TDS. 

We checked. There are no orphaned java processes. No processes are holding /pubapps/icoast/app/prod/content/thredds/cache/collection/GridDatasetInv.dat as far as we can ascertain.

When I try starting tds the server startup goes to the following step:

(base) [icoast@pubweb1 thredds]$ tail -f logs/serverStartup.log
2023-09-29T14:08:35.944-0400 [      6555][        ] WARN  serverStartup: Cannot parse wmsConfig.xml:
2023-09-29T14:08:35.944-0400 [      6555][        ] WARN  serverStartup: Error on line 1 of document http://www.unidata.ucar.edu/schemas/thredds/dtd/ncwms/wmsConfig.dtd: The markup declarations contained or pointed to by the document type declaration must be well-formed.
2023-09-29T14:08:35.988-0400 [      6599][        ] INFO  serverStartup: TdsInit: catalogWriting.useBytesForDataSize= false
2023-09-29T14:08:36.114-0400 [      6725][        ] INFO  serverStartup: Nc4Iosp: NetCDF-4 C library loaded (jna_path='null', libname='netcdf' version='4.3.3.1 of Dec 10 2015 16:44:18 $').
2023-09-29T14:08:36.115-0400 [      6726][        ] INFO  serverStartup: Nc4Iosp: set log level: old=-1 new=0
2023-09-29T14:08:36.119-0400 [      6730][        ] INFO  serverStartup: TdsInit: Aggregation.setTypicalDatasetMode= penultimate
2023-09-29T14:08:36.178-0400 [      6789][        ] INFO  serverStartup: TdsInit: CdmCache= /pubapps/icoast/app/prod/content/thredds/cache/cdm scour = 3600 maxSize = 10000000000
2023-09-29T14:08:36.186-0400 [      6797][        ] INFO  serverStartup: TdsInit: AggregationCache= /pubapps/icoast/app/prod/content/thredds/cache/agg scour = 86400 maxAgeSecs = 7776000
2023-09-29T14:08:36.188-0400 [      6799][        ] INFO  serverStartup: TdsInit: GribIndex=DiskCache2{cachePathPolicy=NestedDirectory, alwaysUseCache=false, cachePathPolicyParam='null', root='/pubapps/icoast/app/prod/content/thredds/cache/grib/', scourEveryMinutes=0, persistMinutes=129600, fail=false}
2023-09-29T14:08:36.200-0400 [      6811][        ] INFO  serverStartup: thredds.server.ncss.controller.NcssDiskCacheNcss.Cache= /pubapps/icoast/app/prod/content/thredds/cache/ncss scour = 600 maxAgeSecs = 300

then it spends  about a minute there and quickly, within a few seconds, gets to the

2023-09-29T14:09:43.940-0400 [     74551][        ] ERROR serverStartup: TdsInit: Failed initialize GridDatasetInv cache= /pubapps/icoast/app/p
rod/content/thredds/cache/collection/

error afterwards with the posted

net.openhft.chronicle.hash.ChronicleHashRecoveryFailedException: net.openhft.chronicle.hash.ChronicleFileLockException: Trying to release lock
on file /pubapps/icoast/app/prod/content/thredds/cache/collection/GridDatasetInv.dat that did not exist

error. What does that error mean? What 'did not exist'?

Would it help if I removed all data directories from the content tree to see if TDS would start up with an empty catalog and then add more data?

**Comment by haileyajohnson** [comment]
> There was an attempt to start another instance of TDS in the same directory tree, but on a different server.

**Comment by moskalenko** [comment]
> > There was an attempt to start another instance of TDS in the same directory tree, but on a different server.

TDS has been running on a webserver for several months with no real issues. We started another webserver, which accidentally attempted to start TDS from the same directory tree. We noticed it and shut it down.
 
> > We're not trying to run two instances.
> 
> Can you please clarify these statements?

We're not able to start a single TDS / tomcat instance at this time.

Thanks,

Alex

**Comment by tdrwenski** [comment]
Were you able to get your TDS working again?

**Comment by moskalenko** [comment]
To summarize, I reinstalled tomcat and TDS, then started TDS without additional content. Then, I moved the old content directory over and didn't see the lock errors. The instance is now working.
