### ISSUE TITLE
Can't access ncml metadata for a dataset in 5.5

### ISSUE THREAD

**Issue by WeatherGod** [Unidata/tds#519]
Don't know why I hadn't noticed this before during development, but I can no longer access the NcML of a dataset via a URL. It keeps coming back as a 404 error. For example: `http://localhost:83/thredds/ncml/ndvi/terra/ndvi_anom_10km` in my local setup no longer works when it used to before. The only change being using 5.5 versus 5.4. I see the service listed in the catalog init logs:

```
...
serviceType (5)
    Service{ name=ncml, base=/thredds/ncml/, typeS=NCML,desc=Provide NCML representation of a dataset.}: count = 20
    Service{ name=ncss, base=/thredds/ncss/, typeS=NetcdfSubset,desc=A web service for subsetting CDM scientific datasets.}: count = 20
    Service{ name=odap, base=/thredds/dodsC/, typeS=OpenDAP,desc=Access dataset through OPeNDAP using the DAP2 protocol.}: count = 20
    Service{ name=wcs, base=/thredds/wcs/, typeS=WCS,desc=Supports access to geospatial data as 'coverages'.}: count = 20
    Service{ name=wms, base=/thredds/wms/, typeS=WMS,desc=Supports access to georegistered map images from geoscience datasets.}: count = 20

ncmlAggSize (1)
             0: count = 20
...
```

and the other services are also working just fine as far as I can tell. I'm doing some more investigating to see if anything custom of mine might be causing problems, but so far I haven't found anything.

**Comment by tdrwenski** [comment]
We removed the threddsIso plugin that provides the ISO, NcML, and UDDC metadata services from the TDS war starting from version 5.5. This was done to fix a circular dependency that made releases very tedious and time consuming. Here are instructions here how to add it back: https://docs.unidata.ucar.edu/tds/5.5/userguide/adding_ogc_iso_services.html#adding-the-plugin. After adding it, I believe the NcML service should work (it seems to be working on thredds.ucar.edu). Please let us know if you have any questions about the instructions!

**Comment by WeatherGod** [comment]
Ah, that's progress (encountered a new error that I need to figure out), but at least it is trying now.

Would it make sense (or possible) to have the ncml service fail to initialize if this file is missing? Bonus points if it can also emit a warning message saying that a jar file may be missing.

**Comment by tdrwenski** [comment]
Thanks for the suggestion, I agree it is not very clear to the user what is going wrong, but not sure I see a good option to help with that at the moment.

I believe a 404 error is what you will get for trying any non-existing service like `.../thredds/foo/mydataset.nc`. You can see all configured services using the admin/debug service at e.g. https://localhost:8443/thredds/admin/spring/showControllers.

If you can't figure out that error, let me know and I can try to have a look!

**Comment by WeatherGod** [comment]
Yeah, this isn't making any sense to me. Here is the log from threddsServlet.log:
```
2024-08-01T20:42:24.875 +0000 [   1247588][     123] INFO  - threddsServlet - Remote host: 172.21.0.1 - Request: "GET /thredds/ncml/gwsc/gdm HTTP/1.1"
2024-08-01T20:42:25.233 +0000 [   1247946][     123] INFO  - ucar.nc2.dataset.conv.DefaultConvention - Unit '' not recognized as a time unit for axis 'time'
2024-08-01T20:42:25.256 +0000 [   1247969][     123] ERROR - thredds.server.metadata.controller.AbstractMetadataController - IOException while trying to get GridDataset:
ncml/gwsc/gdm
2024-08-01T20:42:25.291 +0000 [   1248004][     123] ERROR - thredds.server.metadata.nciso.util.ThreddsExtentUtil - Error in doGetExtentByAxis
java.lang.UnsupportedOperationException: CoordinateAxis1D.getCoordValue() on non-numeric
	at ucar.nc2.dataset.CoordinateAxis1D.getMinValue(CoordinateAxis1D.java:257) ~[cdm-core-5.6.0.jar:5.6.0]
	at thredds.server.metadata.nciso.util.ThreddsExtentUtil.doGetExtentByAxis(ThreddsExtentUtil.java:348) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at thredds.server.metadata.nciso.util.ThreddsExtentUtil.getExtent(ThreddsExtentUtil.java:461) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at thredds.server.metadata.service.EnhancedMetadataService.enhance(EnhancedMetadataService.java:68) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at thredds.server.metadata.controller.NcmlController.handleMetadataRequest(NcmlController.java:119) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
...
```

If I load up the same entry with a sample of data locally using toolsUI, I don't seem to have any issues. Also, WMS, WCS, and OpenDAP work fine as well.

From the opendap page:
```
Dataset {
    Float32 lat[lat = 721];
    Float32 lon[lon = 1440];
    String time[time = 22];
    Grid {
     ARRAY:
        Int32 drought[time = 22][lat = 721][lon = 1440];
     MAPS:
        String time[time = 22];
        Float32 lat[lat = 721];
        Float32 lon[lon = 1440];
    } drought;
    Grid {
     ARRAY:
        Int32 spei01[time = 22][lat = 721][lon = 1440];
     MAPS:
        String time[time = 22];
        Float32 lat[lat = 721];
        Float32 lon[lon = 1440];
    } spei01;
    Grid {
     ARRAY:
        Int32 spei03[time = 22][lat = 721][lon = 1440];
     MAPS:
        String time[time = 22];
        Float32 lat[lat = 721];
        Float32 lon[lon = 1440];
    } spei03;
    Grid {
     ARRAY:
        Int32 spei12[time = 22][lat = 721][lon = 1440];
     MAPS:
        String time[time = 22];
        Float32 lat[lat = 721];
        Float32 lon[lon = 1440];
    } spei12;
} gwsc/gdm;
```

And this problem is happening across all my datasets that represent time in somewhat different ways.

**Comment by tdrwenski** [comment]
Can you send the dataset or a link to where I can download it?

**Comment by WeatherGod** [comment]
Alright, here is the `<dataset>` entry for a different one (but has the same problem). I'll note that the log entry for this one doesn't complain about an empty units string, but still has the same error. I think that is because this one is a `joinExisting` while the other was a `joinNew` for the time dimension.

```
  <dataset urlPath="era5/monthly-summary.nc"
    name="ERA5 Monthly Precipitation and Temperature" ID="era5-monthly-summary">
    <metadata inherited="true">
      <serviceName>all</serviceName>
      <dataType>Grid</dataType>
      <authority>int.ecmwf.era5</authority>
      <documentation type="license" xlink:href="https://apps.ecmwf.int/datasets/licences/copernicus/" xlink:title="Copernicus License"/>
      <documentation type="source" xlink:href="https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5" xlink:title="ECMWF Reanalysis v5 (ERA5)"/>
      <documentation type="attribution">Contains modified Copernicus Climate Change Service information 2021</documentation>
    </metadata>
    <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
      <aggregation type="joinExisting"
          dimName="time"
          recheckEvery="15 min">
        <variableAgg name="t2m"/>
        <variableAgg name="tp"/>
        <scan location="/data/monthly_summary/"
          dateFormatMark="era5-monthly-#yyyy-MM"
          suffix=".nc"/>
      </aggregation>
    </netcdf>
  </dataset>
```

I'm attaching a zip file of two of the files so that an aggregation will occur.
[sample_data.zip](https://github.com/user-attachments/files/16473657/sample_data.zip)

**Comment by tdrwenski** [comment]
Thanks for sending that! With that dataset all of the iso services including NcML are returning a 200 for me. For NcML I get this response
```
<?xml version="1.0" encoding="UTF-8"?>
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" location="Not provided because of security concerns.">
    <attribute name="Conventions" value="CF-1.6" />
    <attribute name="history" value="2022-12-07 16:36:26 GMT by grib_to_netcdf-2.25.1: /opt/ecmwf/mars-client/bin/grib_to_netcdf.bin -S param -o /cache/data5/adaptor.mars.internal-1670430986.4728582-15870-7-95965e43-1136-44fd-aaff-25b8683da44a.nc /cache/tmp/95965e43-1136-44fd-aaff-25b8683da44a-adaptor.mars.internal-1670430985.9452736-15870-10-tmp.grib" />
    <attribute name="_CoordSysBuilder" value="ucar.nc2.internal.dataset.conv.CF1Convention" />
    <dimension name="latitude" length="721" />
    <dimension name="longitude" length="1440" />
    <dimension name="time" length="2" />
    <group name="CFMetadata" />
    <group name="NCISOMetadata">
        <attribute name="metadata_creation" value="2024-08-02" />
        <attribute name="nciso_version" value="2.4.6" />
    </group>
    <variable name="t2m" shape="time latitude longitude" type="float">
        <attribute name="long_name" value="2 Meter Temperature" />
        <attribute name="_FillValue" type="float" value="NaN" />
        <attribute name="units" value="C" />
    </variable>
    <variable name="tp" shape="time latitude longitude" type="float">
        <attribute name="long_name" value="Total Precipitation" />
        <attribute name="_FillValue" type="float" value="NaN" />
        <attribute name="units" value="mm" />
    </variable>
    <variable name="latitude" shape="latitude" type="float">
        <attribute name="long_name" value="latitude" />
        <attribute name="_FillValue" type="float" value="NaN" />
        <attribute name="units" value="degrees_north" />
        <attribute name="_CoordinateAxisType" value="Lat" />
    </variable>
    <variable name="longitude" shape="longitude" type="float">
        <attribute name="long_name" value="longitude" />
        <attribute name="_FillValue" type="float" value="NaN" />
        <attribute name="units" value="degrees_east" />
        <attribute name="_CoordinateAxisType" value="Lon" />
    </variable>
    <variable name="time" shape="time" type="String">
        <attribute name="long_name" value="time coordinate" />
        <attribute name="_CoordinateAxisType" value="Time" />
        <attribute name="standard_name" value="time" />
    </variable>
</netcdf>
```
With that said I am getting the same error written to log: `java.lang.UnsupportedOperationException: CoordinateAxis1D.getCoordValue() on non-numeric`, but it doesn't seem to prevent the request from succeeding.

Are you getting a 404 or 200 response? Do you happen to know if this error was in your logs when you tested with 5.4?

**Comment by WeatherGod** [comment]
Oh, this is interesting... With 5.4 (actually, a development version between 5.4 and 5.5), I get the same exceptions and messages in the logs, but the requests completes with a 200. With 5.5, it completes with a 403:
```
2024-08-06T19:36:24.316 +0000 [    214678][      22] INFO  - threddsServlet - Remote host: 172.24.0.1 - Request: "GET /thredds/ncml/era5/monthly-summary.nc HTTP/1.1"
2024-08-06T19:36:24.405 +0000 [    214767][      22] ERROR - thredds.server.metadata.controller.AbstractMetadataController - IOException while trying to get GridDataset:
ncml/era5/monthly-summary.nc
2024-08-06T19:36:24.442 +0000 [    214804][      22] ERROR - thredds.server.metadata.nciso.util.ThreddsExtentUtil - Error in doGetExtentByAxis
java.lang.UnsupportedOperationException: CoordinateAxis1D.getCoordValue() on non-numeric
	at ucar.nc2.dataset.CoordinateAxis1D.getMinValue(CoordinateAxis1D.java:257) ~[cdm-core-5.6.0.jar:5.6.0]
	at thredds.server.metadata.nciso.util.ThreddsExtentUtil.doGetExtentByAxis(ThreddsExtentUtil.java:348) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at thredds.server.metadata.nciso.util.ThreddsExtentUtil.getExtent(ThreddsExtentUtil.java:461) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at thredds.server.metadata.service.EnhancedMetadataService.enhance(EnhancedMetadataService.java:68) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at thredds.server.metadata.controller.NcmlController.handleMetadataRequest(NcmlController.java:119) [tds-plugin-2.4.6-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
... (rest of traceback) ...
2024-08-06T19:36:24.472 +0000 [    214834][      22] INFO  - threddsServlet - Request Completed - 403 - -1 - 155
```
So, the exception and the warning seems to be a red herring.

So, what would cause geoserver to return a 403 error? The config file I'm using is *exactly* the same as it was for 5.4. Is there something new with 5.5's configs that I missed?

**Comment by tdrwenski** [comment]
Apologies for the delay getting back to you, I was on PTO last week.

I think you probably just need to add:
```
<NCISO>
  <ncmlAllow>true</ncmlAllow>
  <uddcAllow>true</uddcAllow>
  <isoAllow>true</isoAllow>
</NCISO>
```
to your threddsConfig.xml (see also [here](https://docs.unidata.ucar.edu/tds/current/userguide/iso_metadata.html)). Apologies for not making that clearer in the first place-- the default value in the threddsConfig changed from true to false since those ISO services are no longer there by default.

**Comment by WeatherGod** [comment]
I think that did the trick! I'll be doing some more testing over the next 24 hours to see how this goes. Thanks!

**Comment by WeatherGod** [comment]
Everything looks good to me!

**Comment by tdrwenski** [comment]
Thanks for testing and letting us know!

**Comment by tlvu** [comment]
For those using the published docker image here https://hub.docker.com/r/unidata/thredds-docker/tags, the jar `tds-plugin-jar-with-dependencies.jar` seems to be missing from the docker image, see https://github.com/Unidata/thredds-docker/issues/310.
