### ISSUE TITLE
"large" NcML in catalog not working with ChronicleMap (was: Nested aggregation failed in TDS 5)

### ISSUE THREAD

**Issue by geojs** [Unidata/tds#56]
With the latest TDS 5 from :
https://artifacts.unidata.ucar.edu/repository/unidata-snapshots/edu/ucar/tds/5.0.0-SNAPSHOT/tds-5.0.0-20180405.122614-436.war

I have the following error message with OpenDAP (or WMS, HTTPServer) with this URL :
http://localhost:8080/thredds/dodsC/ww3.nc.html

```
Error {
    code = 500;
    message = "barf with read size=1271 in.available=1024";
};
```
The dataset is a union with 2 aggregations by scanning directories.
This configuration works with TDS 4.6.11.

Configuration :
- tomcat-8.5.28
- oracle jdk1.8.0_121
-  catalog.xml
```
  <dataset name="ww3" ID="ww3" urlPath="ww3.nc">
    <metadata inherited="true">
      <serviceName>all</serviceName>
      <dataType>Grid</dataType>
    </metadata>
   <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
    <aggregation type="union">
       <netcdf>
        <aggregation dimName="time" type="joinExisting">    
         <scan location="/ww3/dp/" suffix="*.nc" subdirs="false"/>
        </aggregation>
       </netcdf> 
       <netcdf>
        <aggregation dimName="time" type="joinExisting">    
         <scan location="/ww3/hs/" suffix="*.nc" subdirs="false"/>
        </aggregation>
       </netcdf> 
      </aggregation>
   </netcdf>   
  </dataset>
```

Logs, threddsServlet.log :
```
2018-04-06T12:12:59.672 +0200 [     39309][      10] INFO  - threddsServlet - Remote host: 127.0.0.1 - Request: "GET /thredds/dodsC/ww3.nc.html HTTP/1.1"
2018-04-06T12:12:59.717 +0200 [     39354][      10] ERROR - thredds.server.opendap.OpendapServlet - request= ReqState:
  serverClassName:    'null'
  dataSet:            'ww3.nc'
  requestSuffix:      'html'
  CE:                 ''
  compressOK:          true
  InitParameters:

java.lang.RuntimeException: barf with read size=1271 in.available=1024
	at thredds.server.catalog.tracker.DatasetExt.readExternal(DatasetExt.java:79) ~[tdcommon-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:49) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:30) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.hash.serialization.impl.BytesAsSizedReader.read(BytesAsSizedReader.java:42) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.searchValue(VanillaChronicleMap.java:635) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.tieredValue(VanillaChronicleMap.java:569) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.optimizedGet(VanillaChronicleMap.java:521) ~[chronicle-map-3.14.5.jar:3.14.5]
	at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:470) ~[chronicle-map-3.14.5.jar:3.14.5]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.findResourceControl(DatasetTrackerChronicle.java:185) ~[tdcommon-5.0.0-SNAPSHOT.jar:5.0.0-SNAPSHOT]
	at thredds.core.DatasetManager.resourceControlOk(DatasetManager.java:368) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.core.DatasetManager.openNetcdfFile(DatasetManager.java:133) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.core.TdsRequestedDataset.openAsNetcdfFile(TdsRequestedDataset.java:121) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.core.TdsRequestedDataset.getNetcdfFile(TdsRequestedDataset.java:68) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.getDataset(OpendapServlet.java:878) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.doGetHTML(OpendapServlet.java:552) ~[classes/:5.0.0-SNAPSHOT]
	at thredds.server.opendap.OpendapServlet.doGet(OpendapServlet.java:171) [classes/:5.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.28]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.28]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at thredds.servlet.filter.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:53) [classes/:5.0.0-SNAPSHOT]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at thredds.servlet.filter.RequestCORSFilter.doFilte 
```

The data :
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/dp/ww3.201303_dp.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/dp/ww3.201304_dp.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/dp/ww3.201305_dp.nc

ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/hs/ww3.201303_hs.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/hs/ww3.201304_hs.nc
ftp://ftp.ifremer.fr/ifremer/ww3/HINDCAST/NORGAS/2013/hs/ww3.201305_hs.nc

Thanks

**Comment by lesserwhirls** [comment]
This has taken quite a bit of time to wrap my head around, but here is what I think I understand at this point. In TDS 5, we are using ChronicleMap as a high performance cache, and persist that to disk using protobuf. When reading from the protobuf persistence, we read from an `ObjectInput` using the `read()` method.  Sometimes `read()` does not read the full amount of bytes from the stream, and the content is truncated. If this was the only issue, then switching from `read()` to `fullyRead()` would do the trick, and sometimes it does.

However, I have an example where `fullyRead()` still fails. I'm still trying to understand why, but here is the behavior. I wrote a test using this catalog:

https://github.com/Unidata/tds/pull/57/files#diff-a263226fdd683744e80c38369ae2d651

and the code as is, I get the following error, which is basically what we see in this issue:

~~~bash
java.lang.RuntimeException: barf with read size=3000 in.available=8541

	at thredds.server.catalog.tracker.DatasetExt.readExternal(DatasetExt.java:78)
	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:48)
	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:29)
	at net.openhft.chronicle.hash.serialization.impl.BytesAsSizedReader.read(BytesAsSizedReader.java:43)
	<snip>
~~~

Now, if I change from `read()` to `readFully()`, I get this error:

~~~bash
java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.

	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:51)
	at net.openhft.chronicle.hash.serialization.impl.ExternalizableReader.read(ExternalizableReader.java:29)
	at net.openhft.chronicle.hash.serialization.impl.BytesAsSizedReader.read(BytesAsSizedReader.java:43)
	at net.openhft.chronicle.map.VanillaChronicleMap.searchValue(VanillaChronicleMap.java:628)
~~~

Not quite sure what's happening there.

I noticed that when we add the NcML to the ChronicleMap, we are keeping all of the whitespace and all of the comments, which isn't helping.  That's why moving the NcML to one line and removing whitespace helped, as it reduced the size of the NcML being added to the ChornicleMap. My PR (Unidata/tds#57) makes a change to do that under the hood, and that allows the NcML in my test catalog to work.

Now it's quite possible that there are catalogs with NcML that cannot be made compact enough to work, so this is certainly a bandaid. I still need to dig to see if I can pinpoint the real issue, but I'm worried that the blocking nature of `readFully()` is not playing nice with ChronicleMap...maybe...
